const SHELL_CACHE = 'gereni-shell-v2';
const DATA_CACHE = 'gereni-data-v1';
const FB_CACHE = 'gereni-fb-cache-v1';

const CORE_PRECACHE_URLS = [
  'index.html',
  'menu.html',
  'styles/main.css',
  'styles/print.css',
  'scripts/i18n.js',
  'scripts/theme.js',
  'scripts/headerControls.js',
  'scripts/loadMenu.js',
  'scripts/pdfLink.js',
  'scripts/swRegister.js',
  'data/menu.json',
  'assets/logo-gereni-bar-restaurant.png',
  'assets/photos/Flag_of_Costa_Rica.svg',
  'assets/photos/Flag_of_the_United_States.svg',
  'assets/qr/gereni-menu-qr.png',
  'assets/El_Rancho.jpg',
  'favicon.svg',
  'manifest.webmanifest'
];

// MENU_IMAGES_START - Auto-generated by tools/generate-precache-urls.js
const MENU_IMAGE_URLS = [
  "assets/photos/Chicharrones.png",
  "assets/photos/Quesadillas-a-la-Plancha.png",
  "public/images/Arroz-con-Camarones/Arroz-con-Camarones-1x1-640w.avif",
  "public/images/Arroz-con-Camarones/Arroz-con-Camarones-1x1-640w.jpg",
  "public/images/Arroz-con-Camarones/Arroz-con-Camarones-1x1-640w.webp",
  "public/images/Arroz-con-Camarones/Arroz-con-Camarones-4x3-640w.jpg",
  "public/images/Batidos-en-Leche/Batidos-en-Leche-1x1-1920w.avif",
  "public/images/Batidos-en-Leche/Batidos-en-Leche-1x1-1920w.jpg",
  "public/images/Batidos-en-Leche/Batidos-en-Leche-1x1-1920w.webp",
  "public/images/Batidos-en-Leche/Batidos-en-Leche-4x3-640w.jpg",
  "public/images/Canelones/Canelones-4x3-640w.avif",
  "public/images/Canelones/Canelones-4x3-640w.jpg",
  "public/images/Canelones/Canelones-4x3-640w.webp",
  "public/images/Ceviche-de-Pescado/Ceviche-de-Pescado-1x1-640w.avif",
  "public/images/Ceviche-de-Pescado/Ceviche-de-Pescado-1x1-640w.jpg",
  "public/images/Ceviche-de-Pescado/Ceviche-de-Pescado-1x1-640w.webp",
  "public/images/Ceviche-de-Pescado/Ceviche-de-Pescado-4x3-640w.jpg",
  "public/images/Cordon-Bleu/Cordon-Bleu-1x1-1920w.avif",
  "public/images/Cordon-Bleu/Cordon-Bleu-1x1-1920w.jpg",
  "public/images/Cordon-Bleu/Cordon-Bleu-1x1-1920w.webp",
  "public/images/Cordon-Bleu/Cordon-Bleu-4x3-640w.jpg",
  "public/images/Costillas-BBQ/Costillas-BBQ-1x1-640w.avif",
  "public/images/Costillas-BBQ/Costillas-BBQ-1x1-640w.jpg",
  "public/images/Costillas-BBQ/Costillas-BBQ-1x1-640w.webp",
  "public/images/Costillas-BBQ/Costillas-BBQ-4x3-640w.jpg",
  "public/images/Fajitas-Mixtas/Fajitas-Mixtas-4x3-640w.avif",
  "public/images/Fajitas-Mixtas/Fajitas-Mixtas-4x3-640w.jpg",
  "public/images/Fajitas-Mixtas/Fajitas-Mixtas-4x3-640w.webp",
  "public/images/Filet-Mignon/Filet-Mignon-1x1-640w.avif",
  "public/images/Filet-Mignon/Filet-Mignon-1x1-640w.jpg",
  "public/images/Filet-Mignon/Filet-Mignon-1x1-640w.webp",
  "public/images/Filet-Mignon/Filet-Mignon-4x3-640w.jpg",
  "public/images/Medallones-de-Lomito/Medallones-de-Lomito-1x1-640w.avif",
  "public/images/Medallones-de-Lomito/Medallones-de-Lomito-1x1-640w.jpg",
  "public/images/Medallones-de-Lomito/Medallones-de-Lomito-1x1-640w.webp",
  "public/images/Medallones-de-Lomito/Medallones-de-Lomito-4x3-640w.jpg",
  "public/images/Nuggets-de-Pollo/Nuggets-de-Pollo-1x1-640w.avif",
  "public/images/Nuggets-de-Pollo/Nuggets-de-Pollo-1x1-640w.jpg",
  "public/images/Nuggets-de-Pollo/Nuggets-de-Pollo-1x1-640w.webp",
  "public/images/Nuggets-de-Pollo/Nuggets-de-Pollo-4x3-640w.jpg",
  "public/images/Pozol/Pozol-1x1-640w.avif",
  "public/images/Pozol/Pozol-1x1-640w.jpg",
  "public/images/Pozol/Pozol-1x1-640w.webp",
  "public/images/Pozol/Pozol-4x3-640w.jpg",
  "public/images/antojitos-chalupa/antojitos-chalupa-4x3-1920w.avif",
  "public/images/antojitos-chalupa/antojitos-chalupa-4x3-1920w.jpg",
  "public/images/antojitos-chalupa/antojitos-chalupa-4x3-1920w.webp",
  "public/images/antojitos-chalupa/antojitos-chalupa-4x3-640w.jpg",
  "public/images/antojitos-hamburguesa-gereni/antojitos-hamburguesa-gereni-16x9-1920w.avif",
  "public/images/antojitos-hamburguesa-gereni/antojitos-hamburguesa-gereni-16x9-1920w.jpg",
  "public/images/antojitos-hamburguesa-gereni/antojitos-hamburguesa-gereni-16x9-1920w.webp",
  "public/images/antojitos-hamburguesa-gereni/antojitos-hamburguesa-gereni-4x3-640w.jpg",
  "public/images/antojitos-nachos/antojitos-nachos-4x3-1280w.avif",
  "public/images/antojitos-nachos/antojitos-nachos-4x3-1280w.jpg",
  "public/images/antojitos-nachos/antojitos-nachos-4x3-1280w.webp",
  "public/images/antojitos-nachos/antojitos-nachos-4x3-640w.jpg",
  "public/images/bebidas-cafe/bebidas-cafe-4x3-1280w.avif",
  "public/images/bebidas-cafe/bebidas-cafe-4x3-1280w.jpg",
  "public/images/bebidas-cafe/bebidas-cafe-4x3-1280w.webp",
  "public/images/bebidas-cafe/bebidas-cafe-4x3-640w.jpg",
  "public/images/con-arroz-arroz-de-la-casa/con-arroz-arroz-de-la-casa-16x9-1920w.avif",
  "public/images/con-arroz-arroz-de-la-casa/con-arroz-arroz-de-la-casa-16x9-1920w.jpg",
  "public/images/con-arroz-arroz-de-la-casa/con-arroz-arroz-de-la-casa-16x9-1920w.webp",
  "public/images/con-arroz-arroz-de-la-casa/con-arroz-arroz-de-la-casa-4x3-640w.jpg",
  "public/images/con-arroz-casados/con-arroz-casados-4x3-2560w.avif",
  "public/images/con-arroz-casados/con-arroz-casados-4x3-2560w.jpg",
  "public/images/con-arroz-casados/con-arroz-casados-4x3-2560w.webp",
  "public/images/con-arroz-casados/con-arroz-casados-4x3-640w.jpg",
  "public/images/especialidades-filet-de-pollo/especialidades-filet-de-pollo-16x9-1920w.avif",
  "public/images/especialidades-filet-de-pollo/especialidades-filet-de-pollo-16x9-1920w.jpg",
  "public/images/especialidades-filet-de-pollo/especialidades-filet-de-pollo-16x9-1920w.webp",
  "public/images/especialidades-filet-de-pollo/especialidades-filet-de-pollo-4x3-640w.jpg",
  "public/images/gustitos-sopa-azteca/gustitos-sopa-azteca-1x1-1920w.avif",
  "public/images/gustitos-sopa-azteca/gustitos-sopa-azteca-1x1-1920w.jpg",
  "public/images/gustitos-sopa-azteca/gustitos-sopa-azteca-1x1-1920w.webp",
  "public/images/gustitos-sopa-azteca/gustitos-sopa-azteca-4x3-640w.jpg",
  "public/images/para-el-cafe-club-sandwich/para-el-cafe-club-sandwich-4x3-1280w.avif",
  "public/images/para-el-cafe-club-sandwich/para-el-cafe-club-sandwich-4x3-1280w.jpg",
  "public/images/para-el-cafe-club-sandwich/para-el-cafe-club-sandwich-4x3-1280w.webp",
  "public/images/para-el-cafe-club-sandwich/para-el-cafe-club-sandwich-4x3-640w.jpg"
];
// MENU_IMAGES_END

// Combine core URLs with dynamically generated menu image URLs
const PRECACHE_URLS = [...CORE_PRECACHE_URLS, ...MENU_IMAGE_URLS];

const DATA_PRECACHE_URLS = ['data/menu.json'];

const resolveUrl = (path) => new URL(path, self.location).toString();

const isSameOrigin = (request) => new URL(request.url).origin === self.location.origin;

self.addEventListener('install', (event) => {
  // Activate the service worker immediately so caching works on first load.
  self.skipWaiting();
  event.waitUntil(
    (async () => {
      const shellCache = await caches.open(SHELL_CACHE);
      await shellCache.addAll(
        PRECACHE_URLS.map((path) => new Request(resolveUrl(path), { cache: 'reload' }))
      );

      const dataCache = await caches.open(DATA_CACHE);
      await dataCache.addAll(
        DATA_PRECACHE_URLS.map((path) => new Request(resolveUrl(path), { cache: 'reload' }))
      );
    })()
  );
});

self.addEventListener('activate', (event) => {
  // Remove old caches that do not match the current version.
  const currentCaches = [SHELL_CACHE, DATA_CACHE, FB_CACHE];
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith('gereni-') && !currentCaches.includes(key))
            .map((key) => caches.delete(key))
        )
      )
      .then(() => self.clients.claim())
  );
});

const isFacebookEmbedRequest = (request) => {
  if (request.method !== 'GET') {
    return false;
  }

  const { origin, pathname } = new URL(request.url);

  if (origin === 'https://connect.facebook.net') {
    // Facebook SDK loader.
    return pathname.endsWith('/sdk.js');
  }

  if (origin === 'https://www.facebook.com') {
    // The page plugin iframe content.
    return pathname.startsWith('/plugins/page.php');
  }

  return false;
};

const cacheFirst = async (request) => {
  const cache = await caches.open(SHELL_CACHE);
  const cached = await cache.match(request);
  if (cached) {
    return cached;
  }

  const response = await fetch(request);
  if (response && response.ok) {
    cache.put(request, response.clone());
  }
  return response;
};

const staleWhileRevalidateShell = async (request, event) => {
  const cache = await caches.open(SHELL_CACHE);
  const cached = await cache.match(request);

  let fetchError;
  const networkFetch = fetch(request)
    .then((response) => {
      if (response && response.ok) {
        cache.put(request, response.clone());
      }
      return response;
    })
    .catch((error) => {
      fetchError = error;
      return undefined;
    });

  if (event) {
    event.waitUntil(networkFetch.then(() => undefined));
  }

  if (cached) {
    return cached;
  }

  const networkResponse = await networkFetch;
  if (networkResponse) {
    return networkResponse;
  }

  const fallback = await cache.match(request);
  if (fallback) {
    return fallback;
  }

  if (fetchError) {
    throw fetchError;
  }

  throw new Error('Network request failed and no cache available.');
};

const networkFirstData = async (request) => {
  const cache = await caches.open(DATA_CACHE);
  try {
    const response = await fetch(new Request(request, { cache: 'reload' }));
    if (response && response.ok) {
      cache.put(request, response.clone());
      return response;
    }
    throw new Error(`Network response not ok: ${response.status}`);
  } catch (error) {
    const cached = await cache.match(request);
    if (cached) {
      return cached;
    }
    throw error;
  }
};

const handleNavigation = async (request) => {
  try {
    const response = await fetch(new Request(request, { cache: 'reload' }));
    if (response && response.ok) {
      const cache = await caches.open(SHELL_CACHE);
      cache.put(request, response.clone());
      return response;
    }
    throw new Error(`Network response not ok: ${response.status}`);
  } catch (error) {
    const cache = await caches.open(SHELL_CACHE);
    const url = new URL(request.url);
    const fallbackPaths = [];
    if (url.pathname.endsWith('/menu.html')) {
      fallbackPaths.push('menu.html');
    }
    fallbackPaths.push('index.html');

    for (const path of fallbackPaths) {
      const cached = await cache.match(resolveUrl(path));
      if (cached) {
        return cached;
      }
    }
    throw error;
  }
};

const handleFacebookRequest = async (request, event) => {
  const cache = await caches.open(FB_CACHE);
  const cached = await cache.match(request);

  const networkFetch = fetch(request)
    .then((response) => {
      if (response && (response.ok || response.type === 'opaque')) {
        cache.put(request, response.clone());
      }
      return response;
    })
    .catch((error) => {
      if (cached) {
        return cached;
      }
      throw error;
    });

  if (cached) {
    event.waitUntil(networkFetch.catch(() => undefined));
    return cached;
  }

  return networkFetch;
};

self.addEventListener('fetch', (event) => {
  const { request } = event;

  if (request.method !== 'GET') {
    return;
  }

  if (request.cache === 'only-if-cached' && request.mode !== 'same-origin') {
    return;
  }

  if (isFacebookEmbedRequest(request)) {
    event.respondWith(handleFacebookRequest(request, event));
    return;
  }

  if (!isSameOrigin(request)) {
    return;
  }

  const url = new URL(request.url);

  if (request.mode === 'navigate') {
    event.respondWith(handleNavigation(request));
    return;
  }

  if (url.pathname.endsWith('/data/menu.json')) {
    event.respondWith(networkFirstData(request));
    return;
  }

  if (
    url.pathname.startsWith('/styles/') ||
    url.pathname.startsWith('/scripts/') ||
    url.pathname.endsWith('.css') ||
    url.pathname.endsWith('.js')
  ) {
    event.respondWith(staleWhileRevalidateShell(request, event));
    return;
  }

  event.respondWith(cacheFirst(request));
});
