name: Update Menu Artifacts

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'
      - 'styles/**'
      - 'scripts/**'
      - 'menu.html'
      - 'index.html'
      - 'assets/**'
      - 'tools/**'
      - 'package-lock.json'
      - 'package.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Sync menu JSON
        run: node tools/sync-menu.js

      - name: Run validations
        run: npm run check:all

      - name: Export menu PDFs
        run: npm run export:menu

      - name: Detect changes
        id: changes
        run: |
          if [[ -n "$(git status --porcelain menu.html data/menu.json output/Menu_Gereni_digital.pdf output/Menu_Gereni_digital_*.pdf output/Menu_Gereni_print.pdf)" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push
        if: steps.changes.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add menu.html data/menu.json output/Menu_Gereni_digital.pdf output/Menu_Gereni_digital_*.pdf output/Menu_Gereni_print.pdf
          git commit -m "chore: auto-update menu artifacts [skip ci]"
          git push
